### ISSUE TITLE
Questions about the website

### ISSUE THREAD

**Issue by Evavic44** [devtowntech/website#1]
- [ ] Do we have any design ideas for the website
- [ ] What is the website all about?
- [ ] What languages will we be using to build it?

**Comment by EO4wellness** [comment]
I just saw the discord announcement today. Is it over?

**Comment by Evavic44** [comment]
> 
> 
> I just saw the discord announcement today. Is it over?

No, it's not @EO4wellness. Still waiting on the answers.

**Comment by Evavic44** [comment]
> 
> 
> ok. not certain how to participate

The moderators aren't really responsive to the project. Until then, no development can be done.
